name: TopPVP
main: com.MoNeYBaGS_.TopPVP
version: 0.9

commands:
   kills:
      description: View your kills.
      usage: /kills
   deaths:
      description: View your deaths.
      usage: /deaths
   kdr:
      description: View your Kill/Death ratio.
      usage: /kdr
   resetkills:
      description: Reset a player's kills.
      usage: /resetkills <player>
   resetdeaths:
      description: Reset a player's deaths.
      usage: /resetdeaths <player>
   pvphelp:
      description: View the commands for TopPVP.
      usage: /pvphelp
   leadkills:
      description: View the Kills Leaderboards.
      usage: /leadkills
   leaddeaths:
      description: View the Deaths Leaderboards.
      usage: /leaddeaths
   leadkdr:
      description: View the KDR Leaderboards.
      usage: /leadkdr
   setkills:
      description: Set a player's kill count.
      usage: /setkills <player> <amount>
   setdeaths:
      description: Set a player's death count.
      usage: /setdeaths <player> <amount>